#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       harbour-text-extractor

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    My SailfishOS Application
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    MIT
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-text-extractor.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   libtiff
Requires:   qt5-qtimageformats-plugin-tiff
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Short description of my SailfishOS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install
mkdir %{buildroot}%{_datadir}/%{name}/lib/
mkdir %{buildroot}%{_datadir}/%{name}/tessdata/
cp -f /usr/lib/libtesseract.so.3 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/liblept.so.4 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/share/tessdata/eng.traineddata %{buildroot}%{_datadir}/%{name}/tessdata/
cp -f /usr/share/tessdata/fin.traineddata %{buildroot}%{_datadir}/%{name}/tessdata/

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/%{name}/lib/*
%{_datadir}/%{name}/tessdata/*
# >> files
# << files
