# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-textractor

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^libtesseract|libjpeg|libpng|libnss3|libsmime3|libssl3|libnssutil3|libnspr4|libplc4|libplds4|libexif\\.so\\.12|libc\\.so\\.6\\(GLIBC_2\\.11\\)|libpoppler-qt5\\.so\\.1|libQt5Widgets\\.so\\.5|libfreetype\\.so\\.6|libpoppler\\.so\\.63|liblept.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Optical character recognition application.
Version:    0.7
Release:    0
Group:      Qt/Qt
License:    MIT
URL:        http://skvark.github.io/Textractor/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-textractor.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Textractor is and OCR application made with Tesseract OCR and Leptonica.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    VERSION='%{version}-%{release}'

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
mkdir %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libtesseract.so.3 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/liblept.so.5 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libjpeg.so.62 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libpng15.so.15 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libexif.so.12 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libpoppler-qt5.so.1 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libQt5Widgets.so.5 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libfreetype.so.6 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libpoppler.so.63 %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libnss3.so %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libnssutil3.so %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libssl3.so %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libsmime3.so %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libnspr4.so %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libplc4.so %{buildroot}%{_datadir}/%{name}/lib/
cp -f /usr/lib/libplds4.so %{buildroot}%{_datadir}/%{name}/lib/

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
# >> files
%defattr(0644,root,root,0755)
%attr(0755,-,-) %{_bindir}/%{name}
# << files
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/harbour-textractor/lib/*
